### PR TITLE
Hello-Microverse-2

### PR DESCRIPTION
**Pull request by Minuu7**
- [ ]  Added .gitignore
- [ ] Added Node modules
- [ ] Added linters 
- [ ] Added HTML & CSS
- [ ] Added test.md

### CODE REVIEW

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @Minuu7, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Try-Again

> ## (Highlights) Good Points: 💪 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._
In the case of README consider not leaving any of the sections in the [Microverse README](https://github.com/microverseinc/readme-template) template as it's a project requirement.

| professional Readme  | Your Readme that is not professional |
| ------------- | ------------- |
|  Recording 2023-02-14 at 12 52 20 (5)	  | Recording 2023-02-14 at 12 56 00  |

- [ ] You can't just use `First-Branch` as a branch name. I kindly suggest that you make of a action or feature branch name descriptive e.g `created-Hello-Microverse`. Please kindly check [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for how to rename your branch or you can create a new feature branch and pull request and use a feature or action name for your branch e.g `created-Hello-Microverse` for your branch.



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Minuu7** [comment]
Hello @topeogunleye , please check my correction and let me know if I can go ahead. Thank you.

**Comment by topeogunleye** [comment]
> Hello @topeogunleye , please check my correction and let me know if I can go ahead. Thank you.

Can you please kindly change your branch name @Minuu7 and Instead of React.js, Postgres, and express.js. Remove those, then add the technologies you used e.g `HTML`, `CSS`.

Learn how to change your branch name from this [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) under:
image

or create a new branch and pull request with a proper naming, then mention this Pull request at the bottom of your new Pull request.

@Minuu7, please can you kindly provide me with your previous pull request so that I'll know whether to make this an optional or required requirement.

also, you don't need to create a new pull request or repo for every rereview unless the Reviewer asked you to like I did above

**Comment by topeogunleye** [comment]
> Hello @topeogunleye , please check my correction and let me know if I can go ahead. Thank you.

@Minuu7 Feel free to send me a Zoom call for more questions.

**Pull request closed without merging**
